### ISSUE TITLE
Feat(Docs) : Set up JSDOC website

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#104]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

There is not documentation website set up , i don't know what this or that code / components does

## **Describe the solution you'd like**

A solution involving JSDOC , which converts the JSDOC to a website 

## **Describe alternatives you've considered**

Manually write the docs

**Comment by swarajbachu** [comment]
#116  its done
