### ISSUE TITLE
[VIA-21] Change the "Give Judges Voting Power" checkmark to instead be a toggle saying "Custom judges" or "Funders are judges"

### ISSUE THREAD

**Issue by haonchon** [viaprize/viaprize#338]
<sub>From [SyncLinear.com](https://synclinear.com) | [VIA-21](https://linear.app/viaprize/issue/VIA-21/change-the-give-judges-voting-power-checkmark-to-instead-be-a-toggle)</sub>

**Comment by swarajbachu** [comment]
fixed on #359
