### ISSUE TITLE
Enhance : Find A Privy Alternative For auth

### ISSUE THREAD

**Issue by swarajbachu** [viaprize/viaprize#46]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

The current issue is that , Privy is an awesome tool for auth , web3 and web2 self custody auth is seamless to work with but the there are issues like its expensive , closed source and the on ramp isn't  available in free tier .
---

## **Describe the solution you'd like**

So basically we are looking for an alternative auth provider which is 

1. Open source ( medium priority)
2.  Has a decent free tier or can be self hosted ( high priority)
3. Has onramp feature for free tier also ( high priority)
4. Is self custodial ( high priority ) 

---

## **Describe alternatives you've considered**

So far we are looking at these options 
1. [Torus.us](https://torus.us/) is web3auth. Shamir secret sharing
Competitor to privy.

2.[Entropy.xyz](https://entropy.xyz/) 

3.Lit protocol 

---

### **Additional context**

If you have any other alternative ,then lets continue the chat here , else we can discuss on the (telegram community)[https://t.me/+QsphrF50bv43ZTg5]

**Comment by dipanshuhappy** [comment]
Thinking of torus

**Comment by dipanshuhappy** [comment]
> @dipanshuhappy  should we close this issue?

Nah if there is a better alternative than privy then we would definitely switch
