### ISSUE TITLE
Feat(UI): Username Feature in User Onboarding Page 

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#48]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

The current onboarding page which is at [this](https://github.com/viaprize/viaprize/blob/main/apps/client/pages/onboarding/index.tsx) only takes in email and name , but we need a username feature because it would be easier for the user to share and send profiles , plus easily query his/her profile 

---

## **Describe the solution you'd like**

1. A simple input text box which takes in username. 
2. The text box should be connected to a state.
3. The UI should look good in phone , tablet and PC views 
---

## **Describe alternatives you've considered**

No alternatives 

---

### **Additional context**

1. Use Mantine UI library , avoid unnecessary tailwind css
2. This issue is linked to its backend which is at [here](https://github.com/viaprize/viaprize/issues/47)
3. The issue is linked to its [integrations issue](https://github.com/viaprize/viaprize/issues/49)

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by deeksharungta** [comment]
hey, i would like to work on this issue. please consider assigning it to me.

**Comment by dipanshuhappy** [comment]
> hey, i would like to work on this issue. please consider assigning it to me.

Hey! . Nice to have you here ...
Can you give an estimate on how long it would take you ?


Plus did you have time to set up the monorepo ?

**Comment by dipanshuhappy** [comment]
@deeksharungta  how did you get to know about this repo , it was a pleasant surprise to see a developer here without any marketing done for this repo .

**Comment by deeksharungta** [comment]
> > hey, i would like to work on this issue. please consider assigning it to me.
> 
> Hey! . Nice to have you here ... Can you give an estimate on how long it would take you ?
> 
> Plus did you have time to set up the monorepo ?

I'll try to finish it by tonight, and I haven't set up the monorepo yet.

**Comment by deeksharungta** [comment]
> @deeksharungta how did you get to know about this repo , it was a pleasant surprise to see a developer here without any marketing done for this repo .

I found the repo on goodfirstissues.com

**Comment by dipanshuhappy** [comment]
> > > hey, i would like to work on this issue. please consider assigning it to me.
> > 
> > 
> > Hey! . Nice to have you here ... Can you give an estimate on how long it would take you ?
> > Plus did you have time to set up the monorepo ?
> 
> I'll try to finish it by tonight, and I haven't set up the monorepo yet.


Awesome ! this should be quick and let me know if you face any issue

**Comment by dipanshuhappy** [comment]
> > @deeksharungta how did you get to know about this repo , it was a pleasant surprise to see a developer here without any marketing done for this repo .
> 
> I found the repo on goodfirstissues.com


This is awesome news for viaprize !

**Comment by haonchon** [comment]
@deeksharungta feel free to join our community telegram hub! https://t.me/+QsphrF50bv43ZTg5

**Comment by deeksharungta** [comment]
Hey, I'm trying to set up the development environment, but I couldn't find any documentation related to it. Could you please help me with the commands to download the necessary packages so that I can start coding?

**Comment by deeksharungta** [comment]
> > Hey, I'm trying to set up the development environment, but I couldn't find any documentation related to it. Could you please help me with the commands to download the necessary packages so that I can start coding?
> 
> using npm do `npm i` then cd into the frontend like `cd apps/client` and run npm run dev
> 
> also you can use pnpm too
> 
> dont use yarn ... doesnt seem to work

I tried running that but i'm still getting this error  
❌ Invalid environment variables: {
  NEXT_PUBLIC_CHAIN: [ 'Required' ],
  NEXT_PUBLIC_WEB3_STORAGE: [ 'Required' ],
  NEXT_PUBLIC_PRIVY_APP_ID: [ 'Required' ]
}
- error Failed to load next.config.mjs

**Comment by dipanshuhappy** [comment]
> > > Hey, I'm trying to set up the development environment, but I couldn't find any documentation related to it. Could you please help me with the commands to download the necessary packages so that I can start coding?
> > 
> > 
> > using npm do `npm i` then cd into the frontend like `cd apps/client` and run npm run dev
> > also you can use pnpm too
> > dont use yarn ... doesnt seem to work
> 
> I tried running that but i'm still getting this error ❌ Invalid environment variables: { NEXT_PUBLIC_CHAIN: [ 'Required' ], NEXT_PUBLIC_WEB3_STORAGE: [ 'Required' ], NEXT_PUBLIC_PRIVY_APP_ID: [ 'Required' ] }
> 
>     * error Failed to load next.config.mjs

create a file in the client folder calledn `.env`

then write this is the .env

```
NEXT_PUBLIC_CHAIN=op
NEXT_PUBLIC_WEB3_STORAGE=life-is-to-short
NEXT_PUBLIC_PRIVY_APP_ID=privy
NEXT_PUBLIC_NETWORK_TYPE=mainnet
```


we haven't made dev env variables .. that why some variables can be anything for now

**Comment by deeksharungta** [comment]
> > > > Hey, I'm trying to set up the development environment, but I couldn't find any documentation related to it. Could you please help me with the commands to download the necessary packages so that I can start coding?
> > > 
> > > 
> > > using npm do `npm i` then cd into the frontend like `cd apps/client` and run npm run dev
> > > also you can use pnpm too
> > > dont use yarn ... doesnt seem to work
> > 
> > 
> > I tried running that but i'm still getting this error ❌ Invalid environment variables: { NEXT_PUBLIC_CHAIN: [ 'Required' ], NEXT_PUBLIC_WEB3_STORAGE: [ 'Required' ], NEXT_PUBLIC_PRIVY_APP_ID: [ 'Required' ] }
> > ```
> > * error Failed to load next.config.mjs
> > ```
> 
> create a file in the client folder calledn `.env`
> 
> then write this is the .env
> 
> ```
> NEXT_PUBLIC_CHAIN=op
> NEXT_PUBLIC_WEB3_STORAGE=life-is-to-short
> NEXT_PUBLIC_PRIVY_APP_ID=privy
> NEXT_PUBLIC_NETWORK_TYPE=mainnet
> ```
> 
> we haven't made dev env variables .. that why some variables can be anything for now

Server Error
Error: Cannot initialize the Privy provider with an invalid Privy app ID

**Comment by dipanshuhappy** [comment]
clj3fyjbc005hl908rg61eo9v

**Comment by deeksharungta** [comment]
> > > > > > Hey, I'm trying to set up the development environment, but I couldn't find any documentation related to it. Could you please help me with the commands to download the necessary packages so that I can start coding?
> > > > > 
> > > > > 
> > > > > using npm do `npm i` then cd into the frontend like `cd apps/client` and run npm run dev
> > > > > also you can use pnpm too
> > > > > dont use yarn ... doesnt seem to work
> > > > 
> > > > 
> > > > I tried running that but i'm still getting this error ❌ Invalid environment variables: { NEXT_PUBLIC_CHAIN: [ 'Required' ], NEXT_PUBLIC_WEB3_STORAGE: [ 'Required' ], NEXT_PUBLIC_PRIVY_APP_ID: [ 'Required' ] }
> > > > ```
> > > > * error Failed to load next.config.mjs
> > > > ```
> > > 
> > > 
> > > create a file in the client folder calledn `.env`
> > > then write this is the .env
> > > ```
> > > NEXT_PUBLIC_CHAIN=op
> > > NEXT_PUBLIC_WEB3_STORAGE=life-is-to-short
> > > NEXT_PUBLIC_PRIVY_APP_ID=privy
> > > NEXT_PUBLIC_NETWORK_TYPE=mainnet
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > we haven't made dev env variables .. that why some variables can be anything for now
> > 
> > 
> > Server Error Error: Cannot initialize the Privy provider with an invalid Privy app ID
> 
> try using this

it's working now. thank you!
