### ISSUE TITLE
Feat(DevOps): MonoRepo Set Up Config Done 

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#50]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

Implement a MonoRepo Fully using turbo pack, so that shared builds, packages and development environment are all seamless

---

## **Describe the solution you'd like**

*
We plan on using turbo pack due to its fast build and great support with next js 
---

## **Describe alternatives you've considered**

Not using monorepo , which was a mistake 

---

### **Additional context**

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by swarajbachu** [comment]
done already
