### ISSUE TITLE
Feat(Backend): Create Frontend SDK Client

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#64]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

write now there is no type safety when api is called

---

## **Describe the solution you'd like**

1. Using nestia to convert swagger to client sdk 
2. Connecting client sdk to frontend
3. Using Mock Up Simulator

---

## **Describe alternatives you've considered**

None

---

### **Additional context**

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by swarajbachu** [comment]
is it done?

**Comment by dipanshuhappy** [comment]
@swarajbachu  yes !
