### ISSUE TITLE
Enhance(MonoRepo + Smart Contracts) : Adding the contracts in the monerepo

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#73]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

Write now the smart contracts for a pact and the prizes are in different repos at 
https://github.com/viaprize/pact 
and 
https://github.com/viaprize/Viaprize_contracts 

---

## **Describe the solution you'd like**

1. Using Hardhat environment add these contracts in the mono repo , under the `apps` directory with the folder name `smart-contracts`
2. The smart contracts in the hard hat should be able to deploy 

---

## **Describe alternatives you've considered**

None

---

### **Additional context**

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by dipanshuhappy** [comment]
@Nithin-Varma  can you work on this ?

**Comment by Nithin-Varma** [comment]
Yup

**Comment by Nithin-Varma** [comment]
#102
