### ISSUE TITLE
Enhance(MonoRepo + Smart Contracts) : Adding the Tests to smart contracts Prizes

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#75]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

There is no tests in the smart contracts

---

## **Describe the solution you'd like**

1. Using Hardhat and mocha , write the unit tests of prizes

---

## **Describe alternatives you've considered**

None

---

### **Additional context**

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by Nithin-Varma** [comment]
@dipanshuhappy assign me this, there are some other issues which i can solve but, those issues can be solved by swaraj and tiwari also, so assign me this one.
