### ISSUE TITLE
Enhance(Integrations) : Edit Submission ( $50 )

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#77]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

Integration the Submission 

---

## **Describe the solution you'd like**

Integration the Submission by referring to its related issues 
https://github.com/viaprize/viaprize/issues/76
https://github.com/viaprize/viaprize/issues/59

- One should only be able to edit their submission before the deadline, once the deadline is passed there shouldn't be an option to edit their submission

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by swarajbachu** [comment]
Bounty only after completing the whole part, which includes
UI, backend, and integration
