### ISSUE TITLE
Feat(UI): Voting UI in prizes page

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#79]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

This is still in discussion 

---

## **Describe the solution you'd like**

*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

If you have any issues feel free to discuss here else , we can connect in [telegram group](https://t.me/+QsphrF50bv43ZTg5)

**Comment by swarajbachu** [comment]
Its done, long ago I guess, I will check it once again and close it
