### ISSUE TITLE
Feat(DevOps): Husky Set Up in monorepo

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#88]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

Currently there is no pre commit husky set up 

---

## **Describe the solution you'd like**

1. Make sure husky config is set up 
2. Run eslint pre commit
3. Run prettier pre commit 

---

## **Describe alternatives you've considered**

---

### **Additional context**

If there is any more pre commits , pre push or any other hooks . Do discuss on this issue

**Comment by swarajbachu** [comment]
before merging this we need to work on #94 or else it husky will fail on push

@arrytiwari link your branch or pull request here I will merge it after I fix the above issue

**Comment by arrytiwari** [comment]
I'm closing this issue because i've set the husky but because due to some eslint error there is a problem in testing so the further @swarajbachu  is going to take care of it

**Comment by dipanshuhappy** [comment]
> I'm closing this issue because i've set the husky but because due to some eslint error there is a problem in testing so the further @swarajbachu is going to take care of it

No need to close it manually , if you reference this issue in your pr then once the pr is merged this issue will close automatically

**Comment by swarajbachu** [comment]
lets close it ones it is merged
