### ISSUE TITLE
[Bug] Can't Add Nestia Package to backend

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#89]
# **🐞 Bug Report**

## **Describe the bug**

Can't  seem to install nestia in backend ,
getting this error 

`
error An unexpected error occurred: "expected hoisted manifest for \"nestjs-boilerplate#@nestia/core#@nestjs/platform-express#@nestjs/core\"".
info If you think this is a bug, please open a bug report with the information provided in "/workspaces/viaprize/apps/backend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

### **Is this a regression?**

---

### **To Reproduce**

It should install the package with no issue

---

### **Media prove**

---

### **Your environment**

* OS: Ubuntu
* Node version: 18
* Npm version: latest

---

### **Additional context**

*

**Comment by dipanshuhappy** [comment]
Solved it using npm rather than yarn

**Comment by swarajbachu** [comment]
should we switch to pnpm rather than npm ?, the whole workspace ?

and it is recommended by turbo repo as well
@dipanshuhappy

**Comment by dipanshuhappy** [comment]
closing this issue now since nestia has been added
