### ISSUE TITLE
Feat(Docs): Set up proper read me files for monorepo and frontend 

### ISSUE THREAD

**Issue by dipanshuhappy** [viaprize/viaprize#93]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

The current monorepo does not give a overall view of the proeject , nor anyting at all of the project . 

---

## **Describe the solution you'd like**

1. Add a readme file for monorepo 
2. Monorepo readme file should contain what viaprize is all about ( you can get that from the pitch deck ) 
3. Monorepo readme file should contain info on those folders and files
4. Any other important info related to monorepo
5. Frontend read me should show how to build , run and install repo 

---

## **Describe alternatives you've considered**

None

---

**Comment by dipanshuhappy** [comment]
@swarajbachu  i am not sure why but  yarn doesn't seem to be working with the monorepo while installing  pacakages...
i suggest adding to use npm or pnpm and tell that in the readme file also ...

**Comment by swarajbachu** [comment]
> @swarajbachu i am not sure why but yarn doesn't seem to be working with the monorepo while installing pacakages... i suggest adding to use npm or pnpm and tell that in the readme file also ...

seems to be working for me, can you please send screenshot of the error?

**Comment by dipanshuhappy** [comment]
> > @swarajbachu i am not sure why but yarn doesn't seem to be working with the monorepo while installing pacakages... i suggest adding to use npm or pnpm and tell that in the readme file also ...
> 
> seems to be working for me, can you please send screenshot of the error?

check out the issue at #89
